// examples/vue-basic/src/App.vue
<template>
    <div style="padding: 20px; font-family: sans-serif">
        <h1>Vue 3 + Packem Example</h1>
        <p>This example demonstrates Vue 3 Single File Components (SFCs) with Packem.</p>

        <div style="margin-bottom: 20px">
            <button @click="showCounter = !showCounter">
                {{ showCounter ? "Hide" : "Show" }} Counter
            </button>
        </div>

        <Counter v-if="showCounter" />

        <TodoList />
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import Counter from "./components/Counter.vue";
import TodoList from "./components/TodoList.vue";

const showCounter = ref(true);
</script>

// examples/svelte-basic/src/App.svelte
<script lang="ts">
    import Counter from "./components/Counter.svelte";
    import TodoList from "./components/TodoList.svelte";

    let showCounter = $state(true);
</script>

<div style="padding: 20px; font-family: sans-serif">
    <h1>Svelte 5 + Packem Example</h1>
    <p>This example demonstrates Svelte 5 with Packem.</p>

    <div style="margin-bottom: 20px">
        <button onclick={() => (showCounter = !showCounter)}>
            {showCounter ? "Hide" : "Show"} Counter
        </button>
    </div>

    {#if showCounter}
        <Counter />
    {/if}

    <TodoList />
</div>
